### ISSUE TITLE
Event > Gestion du changement de status

### ISSUE THREAD

**Issue by bronisix** [bronisix/GIG_LINK#48]
- [ ] A la création d'un event, passer un status à "en attente"

- [ ] Création des method "Accept" et "declined" dans le controller events pour changer le status au clic sur le bouton

- [ ] Créer les routes accept et declined PATCH

- [ ] Mettre en place les boutons accepter ou décliner avec la condition if bar.user = current_user

**Comment by hugoPeyronCode** [comment]
git fetch origin
git checkout 48-event-gestion-du-changement-de-status
